import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { runScenario } from './scenario.ts';

// The committed fixtures.json is actual output of this implementation, regenerated by
// `node test/scenario.ts`; the live scenario must keep matching it case for case.
test('the exact-match and mismatch matrix reproduces the committed owned fixtures', () => {
  const owned = JSON.parse(readFileSync(new URL('./fixtures.json', import.meta.url), 'utf8'));
  assert.deepEqual(runScenario(), owned);
});
