// Generate the engine's wire types from its committed protocol schema (docs/capability-kits.md 4.1, BK-P2).
//
// Input:  schema/engine-protocol-1.json — `packages/engine/protocol/schema.json` of the engine at the pin, sha256 in
//         src/constants.ts (ENGINE_SCHEMA_SHA256).
// Output: src/generated/protocol.ts — each verb's flat wire request (the schema's `oneOf` branches), the shared defs,
//         and each verb's result keys read from the schema's `$comment` (the schema types requests only).
//
// Deterministic: test/generated.test.ts regenerates and compares. Run via `npm run gen:write`.
import { compile } from 'json-schema-to-typescript';
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

type Schema = Record<string, unknown>;

// The schema's `$defs` names, renamed so no generated type shadows a global (`error` → `Error`).
const DEF_NAMES: Record<string, string> = {
  platformId: 'WirePlatformId', platformKind: 'WirePlatformKind', rules: 'WireRules', error: 'WireError',
};

const pascal = (verb: string): string => verb.split('.').map((part) => part[0]!.toUpperCase() + part.slice(1)).join('');

/** `voice.parse -> {rules, skipped}; … check -> per draft {fits, …}; …` → keys per verb, and whether it is a list. */
export function resultShapes(comment: string): Record<string, { keys: string[]; list: boolean }> {
  const m = /^Responses: (.*?)\. Bad input -> /.exec(comment);
  if (!m) throw new Error('schema $comment does not start with "Responses: … . Bad input -> "');
  const out: Record<string, { keys: string[]; list: boolean }> = {};
  for (const part of m[1]!.split('; ')) {
    const row = /^([a-z.]+) -> (\[|per [a-z]+ )?\{([^}]*)\}\]?$/.exec(part);
    if (!row) throw new Error(`unreadable response shape in $comment: ${part}`);
    out[row[1]!] = { keys: row[3]!.split(', ').map((key) => key.replace(/\[\]$/, '')), list: row[2] !== undefined };
  }
  return out;
}

export async function generate(schema: Schema): Promise<string> {
  const rewrite = (node: unknown): unknown => {
    if (Array.isArray(node)) return node.map(rewrite);
    if (node === null || typeof node !== 'object') return node;
    return Object.fromEntries(Object.entries(node).map(([k, v]) => {
      if (k === '$ref' && typeof v === 'string') {
        const name = DEF_NAMES[v.replace('#/$defs/', '')];
        if (!name) throw new Error(`unexpected ref: ${v}`);
        return [k, `#/$defs/${name}`];
      }
      return [k, rewrite(v)];
    }));
  };
  const defs: Record<string, unknown> = {};
  for (const [name, def] of Object.entries(schema.$defs as Record<string, Schema>)) {
    const final = DEF_NAMES[name];
    if (!final) throw new Error(`unexpected $defs entry: ${name}`);
    defs[final] = { ...(rewrite(def) as Schema), title: final };
  }
  const verbs: string[] = [];
  for (const branch of schema.oneOf as Schema[]) {
    const props = { ...(branch.properties as Record<string, Schema>) };
    const verb = props.verb?.const;
    if (typeof verb !== 'string' || branch.title !== verb) throw new Error(`oneOf branch without a verb const: ${JSON.stringify(branch.title)}`);
    delete props.verb;
    const name = `${pascal(verb)}Params`;
    defs[name] = {
      type: 'object', title: name, properties: rewrite(props),
      required: (branch.required as string[]).filter((key) => key !== 'verb'), additionalProperties: branch.additionalProperties,
    };
    verbs.push(verb);
  }
  const shapes = resultShapes(String(schema.$comment));
  const missing = verbs.filter((verb) => !(verb in shapes));
  if (missing.length || Object.keys(shapes).length !== verbs.length) throw new Error(`$comment and oneOf disagree on verbs: ${missing.join(', ')}`);

  const compiled = await compile(
    { title: 'Root', $defs: defs, oneOf: Object.keys(defs).map((name) => ({ $ref: `#/$defs/${name}` })) } as never,
    'Root',
    { bannerComment: '', additionalProperties: false },
  );
  const start = compiled.indexOf('export type Root =');
  if (start < 0) throw new Error('unexpected json-schema-to-typescript output');
  const body = compiled.slice(0, start) + compiled.slice(compiled.indexOf(';\n', start) + 2).replace(/^\n+/, '');

  const table = verbs.map((verb) => `  '${verb}': ${pascal(verb)}Params;`).join('\n');
  const results = verbs.map((verb) => {
    const { keys, list } = shapes[verb]!;
    return `  '${verb}': { keys: ${keys.map((key) => `'${key}'`).join(' | ')}; list: ${list} };`;
  }).join('\n');
  return `// Generated by scripts/gen-types.ts from schema/engine-protocol-1.json (docs/capability-kits.md 4.1) — do not edit.\n` +
    `// ${String(schema.title)}. Requests are flat: { verb, ...params }. \`hello\` is outside the schema: the engine answers it\n` +
    `// from \`Protocol.hello()\` in process and \`ownvoice-engine hello\` as a bin.\n\n` +
    `/** Each verb's params as the engine's schema accepts them. */\n` +
    `export interface WireParams {\n${table}\n}\n\n` +
    `export type WireVerb = keyof WireParams;\n` +
    `export type WireRequest = { [V in WireVerb]: { verb: V } & WireParams[V] }[WireVerb];\n\n` +
    `/** Each verb's result keys and whether the result is a list of such objects (from the schema's \`$comment\`). */\n` +
    `export interface WireResults {\n${results}\n}\n\n` +
    body.replace(/\n+$/, '') + '\n';
}

const here = path.dirname(fileURLToPath(import.meta.url));
if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const schema = JSON.parse(readFileSync(path.join(here, '..', 'schema', 'engine-protocol-1.json'), 'utf8')) as Schema;
  writeFileSync(path.join(here, '..', 'src', 'generated', 'protocol.ts'), await generate(schema));
  console.log('wrote src/generated/protocol.ts');
}
