import { cacheKey, decide, type Answer, type Backend, type DecideCache, type Question } from './index.ts';
import { jev } from './jev.ts';
import { openai, UnsupportedAccountError, type OpenAIRequestOptions } from './openai.ts';
import type { ChatGPTPlanAccount } from '@byokit/accounts/chatgpt-plan';
import type { RetryOptions } from './http.ts';

export type DecideConfig = RetryOptions & (
  | { backend: 'jev'; auth: 'apiKey'; model?: 'jev-latest'; via?: 'typesafe' | 'openrouter'; request?: never }
  | { backend: 'openai'; auth: 'apiKey' | 'account'; model: string; request?: OpenAIRequestOptions; via?: never }
);
/** Credentials and fetch stay host-owned; configuration itself is portable JSON. */
export type ConfigHost = {
  keys?: { jev?: string; openai?: string };
  account?: ChatGPTPlanAccount;
  fetch?: typeof fetch;
  /** Separate cache namespace per person/account. Required for account authentication with a cache. */
  cacheScope?: string;
};
export type ConfigOptions = {
  config: DecideConfig;
  host: ConfigHost;
  privacy: 'stays-here' | 'may-leave';
  timeoutMs?: number;
  cache?: DecideCache;
};

export class ConfigError extends Error {
  readonly code = 'invalid_config';
  constructor(message: string) { super(message); this.name = 'ConfigError'; }
}

/** Parse a plain object or JSON string. No environment, file or ambient credential reads. Defaults to Jev. */
export function parseConfig(value: unknown = {}): DecideConfig {
  let v = value;
  if (typeof v === 'string') {
    try { v = JSON.parse(v); } catch { throw new ConfigError('Decision config must be valid JSON.'); }
  }
  if (!v || typeof v !== 'object' || Array.isArray(v) ||
      ![Object.prototype, null].includes(Object.getPrototypeOf(v))) throw new ConfigError('Decision config must be a plain object.');
  const o = v as Record<string, unknown>;
  const allowed = ['backend', 'auth', 'model', 'via', 'request', 'maxRetries', 'retryBaseMs', 'retryMaxMs'];
  if (Object.keys(o).some((k) => !allowed.includes(k))) throw new ConfigError('Unknown decision config field.');
  const backend = o.backend ?? 'jev';
  const auth = o.auth ?? 'apiKey';
  if (backend !== 'jev' && backend !== 'openai') throw new ConfigError('Decision backend must be jev or openai.');
  if (auth !== 'apiKey' && auth !== 'account') throw new ConfigError('Decision auth must be apiKey or account.');
  if (backend === 'jev' && auth === 'account') throw new UnsupportedAccountError('Jev does not support ChatGPT plan authentication.');
  if (backend === 'openai' && (typeof o.model !== 'string' || !o.model.trim())) throw new ConfigError('OpenAI config requires an explicit model.');
  if (backend === 'jev' && o.model !== undefined && o.model !== 'jev-latest') throw new ConfigError('Jev config supports jev-latest.');
  if (o.via !== undefined && (backend !== 'jev' || !['typesafe', 'openrouter'].includes(o.via as string))) throw new ConfigError('via is typesafe or openrouter and only applies to Jev.');
  if (o.request !== undefined && (backend !== 'openai' || !o.request || typeof o.request !== 'object' || Array.isArray(o.request))) throw new ConfigError('request must be an OpenAI request options object.');
  if (o.request && ['model', 'input'].some((k) => Object.hasOwn(o.request as object, k))) throw new ConfigError('model and input are generated by the backend.');
  if (o.request && (o.request as any).text?.format !== undefined) throw new ConfigError('text.format is generated by the backend.');
  if (o.maxRetries !== undefined && (!Number.isSafeInteger(o.maxRetries) || (o.maxRetries as number) < 0)) throw new ConfigError('maxRetries must be a safe non-negative integer.');
  for (const k of ['retryBaseMs', 'retryMaxMs']) {
    if (o[k] !== undefined && (typeof o[k] !== 'number' || !Number.isFinite(o[k]) || o[k] < 0)) throw new ConfigError(`${k} must be a finite number >= 0.`);
  }
  // Take a JSON snapshot: subsequent changes to the host's source object cannot change a saved config.
  let snapshot: Record<string, unknown>;
  try { snapshot = JSON.parse(JSON.stringify(o)); } catch { throw new ConfigError('Decision config must contain JSON data.'); }
  return { ...snapshot, backend, auth } as DecideConfig;
}

export function configuredBackend(o: ConfigOptions): { backend: Backend; config: DecideConfig } {
  const config = parseConfig(o.config);
  if (config.backend === 'jev') return { config, backend: jev({ ...config, key: o.host.keys?.jev ?? '', fetch: o.host.fetch }) };
  if (config.auth === 'apiKey') return { config, backend: openai({ ...config, auth: 'apiKey', key: o.host.keys?.openai ?? '', fetch: o.host.fetch }) };
  if (!o.host.account) throw new UnsupportedAccountError('ChatGPT plan usage needs an account session.');
  if (o.cache && !o.host.cacheScope?.trim()) throw new ConfigError('Account caches require a per-person cacheScope.');
  return { config, backend: openai({ ...config, auth: 'account', account: o.host.account, fetch: o.host.fetch }) };
}

/** Same cache hook as decide, separated by backend/model/request options, billing route and host identity. */
export function configCacheKey(state: unknown, questions: Record<string, Question>, config: DecideConfig, host: ConfigHost): string {
  return cacheKey({ state, config, scope: host.cacheScope,
    credential: config.auth === 'apiKey' ? host.keys?.[config.backend] : undefined }, questions);
}

/** Set configuration once. A per-call partial override replaces provider-specific settings on a backend switch. */
export function createDecider(config: DecideConfig | string | Record<string, unknown>, options: Omit<ConfigOptions, 'config'>) {
  const base = parseConfig(config);
  return (state: unknown, questions: Record<string, Question>, override?: Partial<DecideConfig>): Promise<Record<string, Answer>> => {
    const changed = override?.backend !== undefined && override.backend !== base.backend;
    const shared = changed ? { auth: base.auth, maxRetries: base.maxRetries, retryBaseMs: base.retryBaseMs, retryMaxMs: base.retryMaxMs } : base;
    return decide(state, questions, { ...options, config: parseConfig({ ...shared, ...override }) });
  };
}
