// The pinned Herdr release (docs/runtime-kits.md D5) and the protocol this kit speaks.

export const HERDR_VERSION = '0.9.1';

// From the v0.9.1 schema snapshot (schema/herdr-api-0.9.1.json, docs/runtime-kits.md 6.7);
// regenerated by scripts/gen-types.ts and pinned by test/generated.test.ts.
export const HERDR_PROTOCOL: number = 22;

// Effective accepted server protocols for K11: each undeclared bound means exactly the pin.
export function protocolBounds(range?: { min?: number; max?: number }): { min: number; max: number } {
  return { min: range?.min ?? HERDR_PROTOCOL, max: range?.max ?? HERDR_PROTOCOL };
}
